### ISSUE TITLE
langkit references gnatcoll_iconv, gnatcoll-bindings currently provides gnatcoll-iconv.gpr

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/langkit#10]
Currently libadalang (which includes langkit) fails to build on new gnatcoll.

Source of failure appears to be ./langkit/templates/project_file.mako line: 6.  If "gnatcoll_iconv" is changed to "gnat-iconv" then libadalang builds successfully, at least for me. 

Alternate workaround was to put symbolic link(s) in <install_dir>/share/gpr if this falls into the category of waiting for gnatcoll to stabilize.

**Comment by pmderodat** [comment]
Hello @steve-cs,

Thank you for reporting this. We are aware of this issue and will fix it as soon as possible. We have some internal things to do first, so this could take several days. I hope this is not blocking for you as you already found a workaround. :-)

**Comment by steve-cs** [comment]
A recent commit, https://github.com/AdaCore/gnatcoll-bindings/commit/2fe739ff7be19e934b3a13ead1e20fd472a75495, has resolved this with no further change to langkit needed.
