### ISSUE TITLE
setup.py not installing langkit.lexer

### ISSUE THREAD

**Issue by briot** [AdaCore/langkit#149]
It seems to me that `packages` in `setup.py` should also include `langkit.lexer`.
Otherwise, the directory `langkit/lexer` is not copied when installing, and the compilation
of libadalang fails down the road...

Thanks !

**Comment by pmderodat** [comment]
Hello,

Thanks for reporting this, we’ll fix it. Note that we’ll soon have a Travis CI setup for Langkit, so as suggested a long time ago in <https://github.com/AdaCore/langkit/pull/9>, we should have automated way of detecting these issues soon. :-)

**Comment by pmderodat** [comment]
Hello @briot 

This is now fixed, and our Travis CI setup now uses setup.py, so we should be able to detect future occurences of this issue before they get to the master branch. :-)
