### ISSUE TITLE
StringIO in Python 3

### ISSUE THREAD

**Issue by itoijala-huld** [AdaCore/langkit#353]
The import of `StringIO` in https://github.com/AdaCore/langkit/blob/a33c0222c79a6e403481e7cce5d4439f307995f1/langkit/templates/python_api/module_py.mako#L1274 does not work in Python 3.

It should be `from io import StringIO`.

**Comment by pmderodat** [comment]
Hello,

You are right, thank you for reporting this. We have a candidate fix for this issue: https://github.com/AdaCore/langkit/pull/354 and this issue will automatically be closed when this PR is merged.
