### ISSUE TITLE
GIT message

### ISSUE THREAD

**Issue by mlshore** [AdaCore/langkit#362]
I am using the latest version of Gnat/Ada, and when I compile and run the code I get an error:
 [2020-06-06 16:09:45] Could not locate executable on path: git

The project settings specify Version Control: None

Do I have something incorrectly set, and/or is there a way to suppress this message?

**Comment by pmderodat** [comment]
Hello @mlshore,

This message looks very foreign to Langkit, and I suspect that it comes from GNAT Studio (formerly GPS), so unrelated to Langkit. Can you explain what you are trying to do exactly in order to get this message?

**Comment by pmderodat** [comment]
This issue is probably unrelated to Langkit and we can’t do anything without more information, so closing this issue for now: we’ll reopen it if appropriate later on.
