### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/langkit#391]
While running
```
python ada/manage.py generate -P
```
I got
```
 File "/Volumes/Miscellaneous2/libadalang/venv/src/langkit/langkit/documentation.py", line 27, in <module>
    from typing import (Any, Callable, Dict, List, Optional, Protocol, Set,
ImportError: cannot import name 'Protocol' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

Looks as though we need Python 3.8 now, not the 3.7+ noted in the README?

**Comment by steve-cs** [comment]
Commit https://github.com/AdaCore/langkit/commit/6fa402f0be755cc892a9c4d986dbc4d6c303b2f6 changed the Travis build to 3.8 so that appears to be what Adacore is testing against now.

**Comment by simonjwright** [comment]
Indeed. And 3.8.5 works OK.

**Comment by pmderodat** [comment]
Hello,

Thank you for reporting this inconsistency: we’ll fix the README shortly.
