### ISSUE TITLE
GNAT GPL 2016 encounters a GNAT BUG 

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/langkit#4]
Generating source for libgprlang ...
Generation complete!
Building the generated source code ...
gcc -c -fPIC -gnatwa -gnatyg -g -O0 -gnatwe -gnata -gnatef langkit_support-adalog-main_support.ads
+===========================GNAT BUG DETECTED==============================+
| GPL 2016 (20160515-49) (x86_64-pc-linux-gnu) GCC error:                  |
| in process_type, at ada/gcc-interface/trans.c:9616                       |
| Error detected at langkit_support-adalog-unify_one_side.ads:105:9 [langkit_support-adalog-unify.ads:51:4 [langkit_support-adalog-eq_same.ads:33:4 [langkit_support-adalog-main_support.ads:8:4]]]|
| Please submit a bug report by email to report@adacore.com.               |
| GAP members can alternatively use GNAT Tracker:                          |
| http://www.adacore.com/ section 'send a report'.                         |
| See gnatinfo.txt for full info on procedure for submitting bugs.         |
| Use a subject line meaningful to you and us to track the bug.            |
| Include the entire contents of this bug box in the report.               |
| Include the exact command that you entered.                              |
| Also include sources listed below.                                       |
| Use plain ASCII or MIME attachment(s).                                   |
+==========================================================================+

I ran git bisect; it reports 91cf97e887613dec21dfb543b55360d4274aa28e is the first bad commit

commit 91cf97e887613dec21dfb543b55360d4274aa28e
Author: Pierre-Marie de Rodat <derodat@adacore.com>
Date:   Mon Feb 13 18:05:58 2017 +0100

    astdoc: add documentation for structure types

    TN: Q213-023

I don't understand the code well enough to investigate further

**Comment by pmderodat** [comment]
Hi @stephe-ada-guru,

Yes, we are aware of it, unfortunately (https://travis-ci.org/AdaCore/libadalang). We’ll try to fix it as soon as possible.

**Comment by pmderodat** [comment]
Actually the bug appeared in Langkit with <https://github.com/AdaCore/langkit/commit/47e31874e980a2179d953c1fced98abcb9b890b3>. Anyway, this build failure should now be gone.
