### ISSUE TITLE
Struggling with prefix directory

### ISSUE THREAD

**Issue by AwesomeBiscuitBadger** [AdaCore/langkit#470]
Obviously a noddy question, but not one I can seem to solve. I need to install libadalang so installing this is essential. My GNAT directory is in /opt as the community edition gives. Seems like whichever prefix value I choose I can't seem to get the libadalang installer to find it. Where it is supposed to be if I've got everything in /opt/GNAT?

**Comment by pmderodat** [comment]
Hello @AwesomeBiscuitBadger,

Could you clarify what is the Libadalang installer that you are referring to?

**Comment by AwesomeBiscuitBadger** [comment]
https://github.com/AdaCore/libadalang

**Comment by pmderodat** [comment]
This is a source code repository, so I don’t know what is the installer you are referring to: I don’t have enough information to help here. Could you describe what you have tried (shell commands?) and the error messages you got?

**Comment by pmderodat** [comment]
No answer in several months, so closing this issue (but of course feel free to followup if needed).
