### ISSUE TITLE
langkit is python 2.7 only?

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/langkit#5]
Attempting to build with python 3.5+:
```
Traceback (most recent call last):
  File "ada/manage.py", line 14, in <module>
    from langkit.libmanage import ManageScript
  File "/construction/libadalang/libadalang-611f857/ada/../langkit/langkit/libmanage.py", line 17, in <module>
    from langkit.compile_context import Verbosity
  File "/construction/libadalang/libadalang-611f857/ada/../langkit/langkit/compile_context.py", line 1358
    key=lambda (s, n): n)
               ^
SyntaxError: invalid syntax
```

Python 2.7 is nearly EOL.  In my opinion, no new development should target python 2.7.
At the very least, if this really is a restriction, it should be boldly proclaimed on the README as that is very important build information.

**Comment by pmderodat** [comment]
Considering the huge volume of Python2-only code out there, I think that whether Python 2.7 is nearly EOL is quite debatable. ;-)

Anyway, we plan to support Python3 in the future: doing so will be little work, but we use Python2 in practice and we don’t have the infrastructure to automatically check that Python3 support works for now: we will wait for that first. I’ll add a comment in the README.

Thanks for reporting!

**Comment by jrmarino** [comment]
It's not debatable.  It's been made clear that 2020 is a hard-cutoff (which in itself was already a 5-year extension of the original EOL date).  The amount of important software that hasn't converted or in the process of converting isn't that large, and failure to do so should end in the death of the software in a couple of years.

But yes, I realize it's 2017, 2.5 years before the EOL.  The point was about *new* code should not target python 2.7 only.

For my part, I limited libadalang to python 2.7 only to avoid unexpected build failures.

**Comment by pmderodat** [comment]
Ok. My bet is that there will be another extension, but of course that’s a speculation. I’m sure we’ll support Python3 before 2020. In the meantime I’ve updated the README.

**Comment by jrmarino** [comment]
i would take up up on that bet (meaning I would not make that bet myself).
The people that would be tasked to maintain a 10-year old code base don't want to.  Moreover, these people want migration to python 3, so extending it would impede that goal.  Some corp. would have to pay big bucks to make an extension possible, but I don't know who they would actually pay.

Anyway, I commented on the README commit which I believe you already have seen.

**Comment by Entomy** [comment]
I'm necroposting, but Python 2.7 is _still_ EOL 2020. If updates aren't made, langkit is going to become a legacy liability, not a forward thinking framework.

**Comment by pmderodat** [comment]
As per my previous message, we are aware of this. We’ll make sure it’s compatible with Python3 before 2020.

**Comment by Xiretza** [comment]
> We’ll make sure it’s compatible with Python3 before 2020.

We're almost half-way through 2020 now, with python2 officially dead, and the README still suggests that it doesn't work with python3 at all.

**Comment by jrmarino** [comment]
I strongly hope that gnatstudio 2020 and dependencies doesn't have a python 2.7 requirement.  Adacore products are the only reason python 2.7 is present at all in www.ravenports.com.  I've been waiting until 2020 release to remove it based on the promise that adalang would be updated by 2020.  I really hope that happened.

**Comment by Entomy** [comment]
@Xiretza @jrmarino Looks like they did actually follow through. I am surprised but glad.

![image](https://user-images.githubusercontent.com/25399505/82735858-e23eb300-9cf2-11ea-8022-695b8c37a312.png)

**Comment by Xiretza** [comment]
Unfortunately, this doesn't match up with [`REQUIREMENTS.dev`](https://github.com/AdaCore/langkit/blob/834b66f6fde6f1364ea4b548ec832a63b3f01785/REQUIREMENTS.dev#L7) still containing `enum34`, which wouldn't make any sense if python 3.7 was the official target.

**Comment by Entomy** [comment]
@Xiretza touché

**Comment by raph-amiard** [comment]
@Xiretza This is a dependency of Langkit, which is not needed, nor shipped as such in GNAT community. The Python binding of LAL itself is Python 2 & 3 compatible.

We're working on transitioning Langkit to Python 3 and it should be ready in the following weeks, but also, it shouldn't be needed to use any of AdaCore's user facing software.

Anyway GNATStudio still uses Python 2.X as the embedded interpreter, and while we're working on a solution, it's a much bigger problem because of the variety of user scripts, so don't expect a fully Python 3 ecosystem soon.

**Comment by jrmarino** [comment]
That's very disappointing.  The python EOL deadline has been known to be fixed for 5 years (I would have won that bet referenced 3 years ago).  Honestly it was a questionable design decision to start new software (langkit) based on it.   In a repository system with thousands of packages, gnatstudio and langkit (2019 ecosystem) were literally the only packages incompatible with python 2.
I'd say put a priority on converting the users scripts or just drop them.   There's been literally years to make the transition.

And if python2 is required for building langkit, then it's still required in ravenports (because we have to build it to package it).  And every python package can have dependencies so it multiplies quickly.  I wish you guys had accomplished the goal of 2020, promised 3 years ago.  Some of us took it pretty seriously.

**Comment by Entomy** [comment]
AdaCore: producing legacy software with a focus on backwards compatibility, focusing on never having breaking changes, rather than never having bugs, marketing as if the goal is never having bugs, ignoring actual bug reports, not updating old software to keep bugs from happening, and creating a subculture in the community of attacking other developers for not following the purported goals even though the purported goals aren't happening anyways, since 1994.

**Comment by Entomy** [comment]
People gave me shit for my attitude for years now. I always maintained it was more about their approach and less about me; I don't complain like this about most companies. I think people have been starting to see this past year what I've been noticing for several, between this and other project issues.

**Comment by Xiretza** [comment]
@raph-amiard I'm a packager, so build-time-only python2 dependencies are almost as much of a pain for me as runtime python2 dependencies. I can only join @Entomy in saying it's disappointing that this major issue has only really received attention when everything was already on fire.

**Comment by raph-amiard** [comment]
@Xiretza @jrmarino I understand the concern for packagers, and share the feeling that this should have been done sooner, because it's important for us that our software stays relatively easy to package.

As a piece of maybe not good but comforting news, this will be fixed very soon for Langkit. I'll reopen the issue in the meantime, and you should see movement on this in the following days/weeks.

**Comment by jrmarino** [comment]
Thank you for reopening this very real issue.

**Comment by pmderodat** [comment]
Hello all,

Due to internal constraints, we were not able to fully support Python3 before. We have been working on this for the last three weeks and managed to integrate these changes today. Please let us know if there are still issues related to the version of Ptyhon.

Thank you,
