### ISSUE TITLE
generate, build and install are no longer valid manage.py options

### ISSUE THREAD

**Issue by TamaMcGlinn** [AdaCore/langkit#508]
user_manual/building.rst still claims that you should run `python manage.py generate` (and build, and install), but manage.py rejects those as invalid options.

**Comment by pmderodat** [comment]
Hello,

I believe the manual you are referring to is Libadalang’s (https://github.com/AdaCore/libadalang/blob/master/user_manual/building.rst). It gives instructions to build Libadalang itself, using Libadalang’s own `manage.py` script (https://github.com/AdaCore/libadalang/blob/master/manage.py). Langkit’s script (https://github.com/AdaCore/langkit/blob/master/manage.py) indeed does not handle the `generate` option: if your goal is just to install Langkit’s runtime library (to build Libadalang, for instance), you should use the procedure described here: https://github.com/AdaCore/langkit/#build (also referenced in the Libadalang manual, under the “Setup” section).

Please let us know if you have other issues.
