### ISSUE TITLE
Please support LDFLAGS

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/langkit#647]
This is mainly triggered by use on macOS via Alire.

On macOS, we have to use relocatable builds because static SALs don’t work ([gprbuild issue 97](https://github.com/AdaCore/gprbuild/issues/97)), and this means that we need to provide `libgmp.dylib`.

The macOS compilers available via Alire don’t search `/usr/local` by default, which means that we have to tell gprbuild where to look, and the only obvious mechanism is via `LDFLAGS`.

Please see also [libadalang issue 958](https://github.com/AdaCore/libadalang/issues/958).

**Comment by simonjwright** [comment]
As in [libadalang #958](https://github.com/AdaCore/libadalang/issues/958) I recommend re-closing this.

**Comment by pmderodat** [comment]
Understood, thank you!
