### ISSUE TITLE
Problems installing , --force

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/langkit#657]
This is with v25.0.0.

The top-level `manage.py` doesn't support `--force`, and it should. Instead, I have to say
```
 gprinstall --prefix=$PREFIX --uninstall langkit_support || true
```

The `contrib/{python,lkt)manage.py`'s do support `--force`, but  `./manage.py install --help` doesn't say so.

**Comment by pmderodat** [comment]
Hello again,

We just merged support for `--force`: https://github.com/AdaCore/langkit/commit/d07802d18259f00f4d02f22a90f3269db56bab2d
