### ISSUE TITLE
Missing check in Bind

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/langkit#7]
Found that by writing the following property in `GenericInstantiation`:

~~~python
    xref_equation = Property(
        Bind(Entity.generic_entity_name, Entity.designated_generic_decl)
    )
~~~

The first param should denote a logic variable, but denotes a `T.Name.Entity`, and no error is issued

Thank PM :)

**Comment by pmderodat** [comment]
I have added checks to enforrce that Bind’s first operand is a logic variable and I’ve updated Bind’s documentation accordingly. Thanks for reporting this issue!
